# Generated by Django 5.1.3 on 2024-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(max_length=51)),
                ('type_of_goal', models.CharField(max_length=51)),
                ('text', models.TextField()),
            ],
        ),
    ]
